export const CONFIG = {
  DEFAULT_MIN_COMMITS_PER_DAY: 1,
  DEFAULT_MAX_COMMITS_PER_DAY: 5,
  DEFAULT_BATCH_SIZE: 50,
  MAX_COMMITS_PER_DAY: 10,
  MAX_DATE_RANGE_DAYS: 365,
  RETRY_LIMIT: 3,
  RETRY_DELAY_MS: 3000
};
